
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LBRACKET RBRACKET HASH COLON PERIOD LITERALrule :rule : literal rule\n            | apply rule\n            | generate ruleliteral : LITERAL\n               | PERIOD\n               | COLONapply : HASH LITERAL HASHapply : HASH LITERAL PERIOD modifiers HASHmodifiers : LITERALmodifiers : LITERAL PERIOD modifiersgenerate : LBRACKET LITERAL COLON rule RBRACKET'
    
_lr_action_items = {'HASH':([0,2,4,6,7,8,9,10,15,17,18,19,22,23,24,],[1,1,-6,-5,-7,1,1,15,-8,1,-10,22,-9,-12,-11,]),'PERIOD':([0,2,4,6,7,8,9,10,15,17,18,22,23,],[4,4,-6,-5,-7,4,4,16,-8,4,21,-9,-12,]),'LBRACKET':([0,2,4,6,7,8,9,15,17,22,23,],[5,5,-6,-5,-7,5,5,-8,5,-9,-12,]),'LITERAL':([0,1,2,4,5,6,7,8,9,15,16,17,21,22,23,],[6,10,6,-6,12,-5,-7,6,6,-8,18,6,18,-9,-12,]),'COLON':([0,2,4,6,7,8,9,12,15,17,22,23,],[7,7,-6,-5,-7,7,7,17,-8,7,-9,-12,]),'RBRACKET':([2,4,6,7,8,9,11,13,14,15,17,20,22,23,],[-1,-6,-5,-7,-1,-1,-2,-3,-4,-8,-1,23,-9,-12,]),'$end':([0,2,3,4,6,7,8,9,11,13,14,15,22,23,],[-1,-1,0,-6,-5,-7,-1,-1,-2,-3,-4,-8,-9,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'apply':([0,2,8,9,17,],[8,8,8,8,8,]),'literal':([0,2,8,9,17,],[2,2,2,2,2,]),'modifiers':([16,21,],[19,24,]),'generate':([0,2,8,9,17,],[9,9,9,9,9,]),'rule':([0,2,8,9,17,],[3,11,13,14,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> rule","S'",1,None,None,None),
  ('rule -> <empty>','rule',0,'p_emptyrule','tracery.py',97),
  ('rule -> literal rule','rule',2,'p_rule','tracery.py',101),
  ('rule -> apply rule','rule',2,'p_rule','tracery.py',102),
  ('rule -> generate rule','rule',2,'p_rule','tracery.py',103),
  ('literal -> LITERAL','literal',1,'p_literal','tracery.py',107),
  ('literal -> PERIOD','literal',1,'p_literal','tracery.py',108),
  ('literal -> COLON','literal',1,'p_literal','tracery.py',109),
  ('apply -> HASH LITERAL HASH','apply',3,'p_apply_unmodified','tracery.py',114),
  ('apply -> HASH LITERAL PERIOD modifiers HASH','apply',5,'p_apply_modified','tracery.py',118),
  ('modifiers -> LITERAL','modifiers',1,'p_modifier','tracery.py',123),
  ('modifiers -> LITERAL PERIOD modifiers','modifiers',3,'p_multiple_modifier','tracery.py',127),
  ('generate -> LBRACKET LITERAL COLON rule RBRACKET','generate',5,'p_generate','tracery.py',137),
]
