# -*- Mode: python -*-

Import( 'env' )

Default( env.TraceryContract( 'animal.tracery',
                              contract = 'animal' ) )

env.TraceryContract( 'pet.tracery', contract = 'pet' )
env.TraceryContract( 'bot_teleport.tracery', contract = 'teleport' )

